language: go

os:
  - linux

go:
  - 1.11.x
  - 1.12.x
  - master
  
go_import_path: github.com/vertica/vertica-sql-go
  
before_install:
  - git clone https://github.com/jbfavre/docker-vertica.git
  - curl $VERTICA_CE_URL --create-dirs -o docker-vertica/packages/vertica-ce.latest.rpm
  - docker build -f docker-vertica/Dockerfile.centos.7_9.x --build-arg VERTICA_PACKAGE=vertica-ce.latest.rpm -t jbfavre/vertica docker-vertica
  - docker images
  - docker run --hostname vertica-docker --name vertica_docker -d -p 5433:5433 jbfavre/vertica
  - sleep 60

script:
  - go test --locator localhost:5433 --user dbadmin -race .
  - go test --locator localhost:5433 --user dbadmin --use_prepared_statements=0 -race .
  - go test -race ./logger
  - docker exec -u dbadmin vertica_docker /opt/vertica/bin/vsql -c "SELECT SET_CONFIG_PARAMETER('SSLPrivateKey', '`cat ./resources/tests/ssl/root.key`');"
  - docker exec -u dbadmin vertica_docker /opt/vertica/bin/vsql -c "SELECT SET_CONFIG_PARAMETER('SSLCertificate', '`cat ./resources/tests/ssl/root.crt`');"
  # docker exec -u dbadmin vertica_docker /opt/vertica/bin/vsql -c "ALTER DATABASE docker SET SSLCA='`cat ./resources/tests/ssl/root.crt`';"
  - docker exec -u dbadmin vertica_docker /opt/vertica/bin/vsql -c "ALTER DATABASE docker SET EnableSSL=1;"
  - docker exec -u dbadmin vertica_docker /opt/vertica/bin/admintools --tool stop_db --database docker
  - docker exec -u dbadmin vertica_docker /opt/vertica/bin/admintools --tool start_db --database docker
  - go test --locator localhost:5433 --user dbadmin --tlsmode=server -race .
  - go test --locator localhost:5433 --user dbadmin --tlsmode=server --use_prepared_statements=0 -race .
  # go test --locator localhost:5433 --user dbadmin --tlsmode=server-strict -race .
  # go test --locator localhost:5433 --user dbadmin --tlsmode=server-strict --use_prepared_statements=0 -race .
